### ISSUE TITLE
Step07 | flask-sqlalchemy isn't installed with `pip install flask` anymore?

### ISSUE THREAD

**Issue by e1nh4nd3r** [singingwolfboy/build-a-flask-api#5]
From a fresh copy and environment of this repo:
```
(venv) jgoin@Tsume ~/repos/build-a-flask-api/step07 (master) $ python puppy.py createdb
Traceback (most recent call last):
  File "puppy.py", line 3, in <module>
    from models import db, Puppy
  File "/Users/jgoin/repos/build-a-flask-api/step07/models.py", line 1, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'
```

```
(venv) jgoin@Tsume ~/repos/build-a-flask-api/step07 (master) $ cd ..
(venv) jgoin@Tsume ~/repos/build-a-flask-api (master) $ pip install Flask-SQLAlchemy
Collecting Flask-SQLAlchemy
  Downloading Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl
Requirement already satisfied: Flask>=0.10 in ./venv/lib/python3.6/site-packages (from Flask-SQLAlchemy)
Collecting SQLAlchemy>=0.8.0 (from Flask-SQLAlchemy)
  Downloading SQLAlchemy-1.2.2.tar.gz (5.5MB)
    100% |████████████████████████████████| 5.5MB 220kB/s
Requirement already satisfied: itsdangerous>=0.21 in ./venv/lib/python3.6/site-packages (from Flask>=0.10->Flask-SQLAlchemy)
Requirement already satisfied: Werkzeug>=0.7 in ./venv/lib/python3.6/site-packages (from Flask>=0.10->Flask-SQLAlchemy)
Requirement already satisfied: click>=2.0 in ./venv/lib/python3.6/site-packages (from Flask>=0.10->Flask-SQLAlchemy)
Requirement already satisfied: Jinja2>=2.4 in ./venv/lib/python3.6/site-packages (from Flask>=0.10->Flask-SQLAlchemy)
Requirement already satisfied: MarkupSafe>=0.23 in ./venv/lib/python3.6/site-packages (from Jinja2>=2.4->Flask>=0.10->Flask-SQLAlchemy)
Installing collected packages: SQLAlchemy, Flask-SQLAlchemy
  Running setup.py install for SQLAlchemy ... done
Successfully installed Flask-SQLAlchemy-2.3.2 SQLAlchemy-1.2.2
```

Seems to work afterward.
```
(venv) jgoin@Tsume ~/repos/build-a-flask-api (master) $ cd step07/
(venv) jgoin@Tsume ~/repos/build-a-flask-api/step07 (master) $ python puppy.py createdb
/Users/jgoin/repos/build-a-flask-api/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Database created!
(venv) jgoin@Tsume ~/repos/build-a-flask-api/step07 (master) $ python puppy.py seeddb
/Users/jgoin/repos/build-a-flask-api/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Database seeded!
(venv) jgoin@Tsume ~/repos/build-a-flask-api/step07 (master) $
```

**Comment by cldershem** [comment]
As far as I am aware, `flask-sqlalchemy` has never been installed alongside `flask` and has always been a separate dependency. This is by design since `flask` has no opinion about your ORM or if you need a DB at all. If you'd like to install all of the required dependencies of a project try `pip install -r requirements` or `pipenv install -r path/to/requirements.txt` if using `pipenv`.

**Comment by AmirBekhit** [comment]
I have got the same problem.
all packages are installed , I am using pipenv for virtual environment :

[packages]
flask = "*"
psycopg2 = "*"
psycopg2-binary = "*"
flask-sqlalchemy = "*"
gunicorn = "*"
sqlalchemy = "*"
db = "*"

and when I am trying to got to the terminal in order to { db.create_all()] ; I get this :  ModuleNotFoundError: No module named 'flask_sqlalchemy' . 

I would appreciate if anyone can help me with this 
*ps*  I am still in development and not in production.

**Comment by jamjahal** [comment]
I am having an issue as well loading flask-SQLAlchemy in docker.  I'm not getting an error about any other modules installed through requirements.  
-------------
dockerfile:
------------
```FROM python:3.8.2-slim-buster

WORKDIR /usr/src/app

COPY requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./run.py" ]
---------------

requirements.txt: 
-----------------
```Flask==1.1.2
flask-restful==0.3.8
SQLAlchemy==1.3.16
markdown==2.6.11
Flask-SQLAlchemy==2.4.1
click==7

---------------
__init__.py :
---------------
```
import markdown
import os
import click

# Import the framework
from flask import Flask  # , g, current_app
from flask_restful import Resource, Api, reqparse
from flask_sqlalchemy import SQLAlchemy
# Create an instance of Flask
app = Flask(__name__)

# Create the Api
api = Api(app)

# Create the database connection
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db'
db = SQLAlchemy(app).......

....yada yada yada rest of init code...

--------------------
ERROR MESSAGE:
--------------------
```
(base)$ docker-compose up
Creating savage_view_api_sv_api_1 ... done
Attaching to savage_view_api_sv_api_1
sv_api_1  | Traceback (most recent call last):
sv_api_1  |   File "./run.py", line 1, in <module>
sv_api_1  |     from sv_api import app, db
sv_api_1  |   File "/usr/src/app/sv_api/__init__.py", line 13, in <module>
sv_api_1  |     from flask_sqlalchemy import SQLAlchemy
sv_api_1  | ModuleNotFoundError: No module named 'flask_sqlalchemy'

**Comment by singingwolfboy** [comment]
I can't provide support about installing flask-sqlalchemy.

**Comment by HanslettTheDev** [comment]
I face the same issue developing a crud app with flask. when I run it in development mode I get the error 

flask.cli.NoAppException: While importing "report", an ImportError was raised:

Traceback (most recent call last):
File "C:\Users\TAMBE-PC\anaconda3\lib\site-packages\flask\cli.py", line 240, in locate_app
__import__(module_name)
File "E:\Software Development\Report App\report.py", line 2, in <module>
from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'

I don't know what is happening though I have the module properly installed and  I am not using a virtual env 

need help
