### ISSUE TITLE
Marshmallow.ModelSchema is deprecated

### ISSUE THREAD

**Issue by JDeeth** [singingwolfboy/build-a-flask-api#8]
Marshmallow's `ModelSchema` is deprecated, and dropping in its replacement (`SQLAlchemyAutoSchema`) doesn't seem to work - for instance posting with incomplete data raises an unhandled ValidationError exception.

https://github.com/singingwolfboy/build-a-flask-api/blob/aeef59dc1ef61318d6dc761587b4367fbf853236/step13/schemas.py#L7

(also, thanks very much for the 2016 talk, it was really inspiring!)

**Comment by gavwellis** [comment]
Try this from: https://stackoverflow.com/questions/57984649/marshmallow-object-has-no-attribute-modelschema

```
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow

db = SQLAlchemy(app)
ma = Marshmallow(app) 

# flask-marshmallow<0.12.0

class UserSchema(ma.ModelSchema):
      class Meta:
            model = User

# flask-marshmallow>=0.12.0 (recommended)

from conf import ma
class UserSchema(ma.SQLAlchemyAutoSchema):
      class Meta:
            model = User
            load_instance = True

# flask-marshmallow>=0.12.0 (not recommended)

from marshmallow_sqlalchemy import ModelSchema
class UserSchema(ModelSchema):
      class Meta:
            model = User
            sql_session = db.session

```

**Comment by JDeeth** [comment]
Yup Gav, that's the guidance from the v0.22 release notes for Flask-SQLAlchemy: https://marshmallow-sqlalchemy.readthedocs.io/en/latest/changelog.html#id10

Thanks again for accepting the pull request!
